<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>LibOps</RootNamespace>
    <AssemblyName>LibOps</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UserSecretsId>d95882f8-6e1f-4946-a966-fa0330b1a874</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ApplicationDefinition Include="PresentationLayer\App.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </ApplicationDefinition>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.1" />
    <PackageReference Include="FontAwesome" Version="4.7.0" />
    <PackageReference Include="LiveCharts.Wpf" Version="0.9.7" />
    <PackageReference Include="MahApps.Metro.IconPacks.Material" Version="6.2.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="payOS" Version="2.1.0" />
    <PackageReference Include="QRCoder" Version="1.8.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.Configuration" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\BookCovers\**\*.*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>